service: daily-journal-app-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  httpApi:
    cors: true

plugins:
  - serverless-offline

custom:
  hooks:
    before:deploy:runBuild:
      commands: npm run build:lambda

package:
  patterns:
    - 'lambda/dist/**'
    - 'node_modules/**'
    - '!src/**'
    - '!.env*'
    - '!tsconfig.json'
    - '!codegen.yml'
    - '!schema.graphql'
    - '!.gitignore'

functions:
  graphql:
    handler: lambda/dist/server.handler
    events:
      # - httpApi:
      #     path: /
      #     method: POST
      - httpApi:
          path: /
          method: GET
