service: google-calendar-watcher

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  httpApi:
    cors: true

plugins: 
  -serverless-plugin-typescriptS
  - serverless-offline

functions:
  graphql:
    handler: src/index.handler
    events:
 
      - httpApi:
          path: /
          method: GET

package:
  individually: true